- name: install Apache2
  become: true
  apt:
    name: apache2
    state: present
    update_cache: yes

- name: copy index.html template
  become: true
  template:
    src: index.html
    dest: /var/www/html/index.html
    owner: "{{ apache_data_owner }}"
    group: "{{ apache_data_group }}"
    mode: 0600